# Generated by Django 4.2.9 on 2024-04-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="напишите название",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
            ],
            options={
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=100, verbose_name="текст вопроса"
                    ),
                ),
                (
                    "number",
                    models.IntegerField(
                        unique=True, verbose_name="номер теста"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        help_text="выберите тест",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        related_query_name="questions",
                        to="api.test",
                        verbose_name="тест",
                    ),
                ),
            ],
            options={
                "verbose_name": "вопрос",
                "verbose_name_plural": "вопросы",
            },
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_true", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        help_text="выберите вопрос",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        related_query_name="answers",
                        to="api.question",
                        verbose_name="вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "ответ",
                "verbose_name_plural": "ответы",
            },
        ),
    ]
