# Generated by Django 4.2.9 on 2024-04-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="test",
            options={"verbose_name": "тест", "verbose_name_plural": "тесты"},
        ),
    ]
