# Generated by Django 4.2.9 on 2024-04-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_test_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="text",
            field=models.CharField(
                default=1, max_length=100, verbose_name="текст ответа"
            ),
            preserve_default=False,
        ),
    ]
