# Generated by Django 4.2.9 on 2024-04-04 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_answer_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.IntegerField(verbose_name="номер теста")),
                (
                    "answer",
                    models.ForeignKey(
                        help_text="выберите ответ",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ansusers",
                        related_query_name="ansusers",
                        to="api.answer",
                        verbose_name="ответ",
                    ),
                ),
            ],
            options={
                "verbose_name": "ответ пользователя",
                "verbose_name_plural": "ответы пользователя",
                "unique_together": {("user", "answer")},
            },
        ),
    ]
