# Generated by Django 4.2.9 on 2024-04-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_answeruser_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="is_true",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
