# Generated by Django 4.2.9 on 2024-04-08 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_answer_is_true"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="is_true",
        ),
        migrations.AddField(
            model_name="answer",
            name="ball",
            field=models.PositiveIntegerField(
                default=0, verbose_name="количество балов"
            ),
        ),
    ]
